name: Stayzi CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Kodları indir
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Ortam değişkenlerini ayarla
        run: |
          echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/test_db" >> $GITHUB_ENV
          echo "SECRET_KEY=FAKE_TEST_SECRET_KEY" >> $GITHUB_ENV

      - name: Kütüphaneleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r backend_fastapi/requirements.txt  

      - name: Alembic migration
        run: alembic upgrade head

      - name: Testleri çalıştır
        run: pytest || echo "Test yok"
